language: python
before_install:
- openssl aes-256-cbc -K $encrypted_14007559d628_key -iv $encrypted_14007559d628_iv
  -in gce.json.enc -out gce.json -d
deploy:
  provider: gae
  keyfile: gce.json
  project: game-launcher-1439e
  skip_cleanup: true
  on: production
